In [1]:
import numpy as np

In [7]:
!pip install numpy

In [9]:
array_np = np.array([1,2,3])

In [11]:
array_np

array([1, 2, 3])

In [21]:
#methods
a = np.zeros((2, 3))
b = np.zeros([2, 3])
print(a)
print(b)
print(np.array_equal(a, b))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
True


In [23]:
a = np.ones((2, 3))
b = np.ones([2, 3])
print(a)
print(b)
print(np.array_equal(a, b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
True


In [29]:
a = np.full((2, 3),8)
print(a)

[[8 8 8]
 [8 8 8]]


In [35]:
#arrange element upto limits
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [37]:
# equally spaced
np.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [41]:
#array internal function
np_array = np.array([[1,2,19],[3,4,17]])

In [45]:
np_array.shape

(2, 3)

In [47]:
np_array.size

6

In [49]:
np_array.argmin

<function ndarray.argmin>

In [51]:
np_array.ndim

2

In [53]:
np_array.dtype

dtype('int64')

In [59]:
#dtpe
np_array = np.array([[1,2,19],[3,4,17]],dtype="float32")

In [61]:
np_array

array([[ 1.,  2., 19.],
       [ 3.,  4., 17.]], dtype=float32)